// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-puzr9biwFa7ckFRXN8VbFyAsbjTk2F4',
    appId: '1:1049329557684:web:659a626c209c6ecaa0f7e1',
    messagingSenderId: '1049329557684',
    projectId: 'ruwad-tracking',
    authDomain: 'ruwad-tracking.firebaseapp.com',
    storageBucket: 'ruwad-tracking.appspot.com',
    measurementId: 'G-THJLH5SDD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4n1VLNr2ZG5EKTJV8BOcd64rmEMzR01s',
    appId: '1:1049329557684:android:1ca691b5a1e510d4a0f7e1',
    messagingSenderId: '1049329557684',
    projectId: 'ruwad-tracking',
    storageBucket: 'ruwad-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqsx2KZ0_fep-r6KvQ7ApA8Qj1pf0gYU',
    appId: '1:1049329557684:ios:e4a4e58b58ba48aea0f7e1',
    messagingSenderId: '1049329557684',
    projectId: 'ruwad-tracking',
    storageBucket: 'ruwad-tracking.appspot.com',
    iosBundleId: 'com.example.ruwadRewatib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgqsx2KZ0_fep-r6KvQ7ApA8Qj1pf0gYU',
    appId: '1:1049329557684:ios:e4a4e58b58ba48aea0f7e1',
    messagingSenderId: '1049329557684',
    projectId: 'ruwad-tracking',
    storageBucket: 'ruwad-tracking.appspot.com',
    iosBundleId: 'com.example.ruwadRewatib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-puzr9biwFa7ckFRXN8VbFyAsbjTk2F4',
    appId: '1:1049329557684:web:14564cf9eef918eda0f7e1',
    messagingSenderId: '1049329557684',
    projectId: 'ruwad-tracking',
    authDomain: 'ruwad-tracking.firebaseapp.com',
    storageBucket: 'ruwad-tracking.appspot.com',
    measurementId: 'G-R2JVR4DMX0',
  );
}
